# Generated by Django 6.0 on 2026-05-05 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0077_tagconfig_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecknOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(max_length=30)),
                ('consumer_id', models.CharField(max_length=512)),
                ('consumer_uri', models.URLField(max_length=1024)),
                ('provider_id', models.CharField(blank=True, default='', max_length=255)),
                ('item_id', models.CharField(blank=True, default='', max_length=255)),
                ('fulfillment_id', models.CharField(blank=True, default='', max_length=255)),
                ('billing', models.JSONField(blank=True, default=dict)),
                ('quote', models.JSONField(blank=True, default=dict)),
                ('payment', models.JSONField(blank=True, default=dict)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beckn_order', to='emr.tokenbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BecknTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('message_id', models.UUIDField(db_index=True, unique=True)),
                ('consumer_id', models.CharField(max_length=512)),
                ('consumer_uri', models.URLField(max_length=1024)),
                ('domain', models.CharField(default='nic2004:85111', max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.1.0', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(max_length=20)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('transaction_id', 'action'), name='unique_transaction_action')],
            },
        ),
    ]
